import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import  Navbar  from "@/components/Navbar";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`antialiased h-full flex flex-col `}
      >
        <div className="fixed top-0 left-0 right-0 z-50">
          <Navbar />
        </div>
        
        <main className="flex-1 mt-8">
          {children}
        </main>
        
        <Footer />
      </body>
    </html>
  );
}
